### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by claire-kz** [cmeighen/collabright#1]
- Remove `note` about link to production site.  Make link point to live version.  Remove all later references to `note`
- `Questions track a sufficient amount of data to enable a variety of search angles.` -- what does this mean?  Clarify. 
- Remove Phase4.  Styling should be done as you go along - every feature should be styled in order to be marked complete. 
- Restructure priorities: 1. Ability to create and save posts  2. Ability to comment  3. User homepage  4. tags  5. search

**Comment by cmeighen** [comment]
- Removed note about link to production site. Link currently points to collabright.heroku. Removed further references to note. 
- Reworded this to specify the search options. 
- Replaced Phase4 with time for refactoring. 
- Added User Homepage as an MVP req.
