### ISSUE TITLE
Component Hierarchy

### ISSUE THREAD

**Issue by claire-kz** [cmeighen/collabright#2]
- Remove NBs from sample repo
- Incomplete.  Component hierarchy and routes need to filled out.  Do not correspond to wireframes.  These must be planned out in detail before beginning to code.

**Comment by cmeighen** [comment]
- Removed NB files from sample repo. 
  Component Question: 
  The display for a post has 4 internal sections: 
  • Post title and body.
  • Collaborative student answer
  • Teacher answer
  • Comments

I'm not sure if I should make each of these separate components or build them into one big post detail component.
