### ISSUE TITLE
Flux Cycles

### ISSUE THREAD

**Issue by claire-kz** [cmeighen/collabright#3]
- Remove description of what a flux cycle is 
- Will need post responses for the successful update and creation of a post
- Where is the cycle to create comments? 
- What is `removeSearchSuggestions`?

**Comment by cmeighen** [comment]
- Removed description of flux cycle
- I believe update and create use receive single post as the callback. If this is incorrect and they need separate responses please advise. 
- Added a cycle for creating comments. 
- Removed removeSearchSuggestions, leftover text from the FresherNote proposal.
